server:
  port: 8181
spring:
  application:
    name: trade-service
  cloud:
    config:
      uri:  ${vcap.services.config-server.credentials.uri:http://cloud-config:8888}
eureka:
  client:
    enabled: true
logging:
  level:
    org.springframework: DEBUG