server:
  port: 8181
spring:
  application:
    name: trade-service
  cloud:
    config:
      uri:  ${vcap.services.config-server.credentials.uri:http://cloud-config:8888}
eureka:
  client:
    enabled: true
    instance:
        hostname: ${vcap.services.eureka-service.credentials.uri:http://eureka-server:8761}/eureka/
EUREKA_PORT_8761_TCP_ADDR: ${vcap.services.eureka-service.credentials.uri:localhost}
